# Generated by Django 4.2.7 on 2023-11-07 10:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='nom')),
            ],
            options={
                'verbose_name': 'catégorie de projet',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='nom')),
                ('url', models.URLField(blank=True)),
                ('created', models.CharField(blank=True, help_text='année de création', max_length=4, verbose_name='créé en')),
                ('desc', tinymce.models.HTMLField(blank=True, verbose_name='description')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_work.category')),
                ('image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image_project', to=settings.FILER_IMAGE_MODEL)),
            ],
            options={
                'verbose_name': 'projet',
            },
        ),
    ]
